# Generated by Django 4.2.19 on 2025-02-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateTimeField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponivel'), ('Indisponivel', 'Indisponivel')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
