# Generated by Django 4.2.11 on 2025-02-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_entrada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.servico')),
            ],
        ),
    ]
