# Generated by Django 4.2.11 on 2025-03-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0007_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='servico',
        ),
    ]
