# Generated by Django 4.2.11 on 2025-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0008_remove_vendas_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
